### PR TITLE
patching sublevel

### PR DESCRIPTION
**Pull request by cshum**
To initiate maxogden/dat/#384, patching sublevel is the best possible way I can think of. It respects current sublevel codec and, hopefully should not change any existing behaviours so far.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Link to the issue: https://github.com/maxogden/dat/issues/384

**Comment by okdistribute** [comment]
Wow, great. @mafintosh wouldn't this be backwards compatible, too?

**Comment by mafintosh** [comment]
I'm not super comfortable switching out subleveldown since its a major critical dependency (and by now pretty battle tested in various projects). @cshum why is a new sublevel abstraction needed for this? I tried digging through the code but couldn't find the relevant sql parts

**Comment by okdistribute** [comment]
If I'm not mistaken, in the [original issue](https://github.com/maxogden/dat/issues/384) @cshum  discusses wanting the MySQL backend to respect a table<->dataset association (seen in [myDOWN](https://github.com/cshum/mydown)).  

When I use dat with [sqldown](https://github.com/calvinmetcalf/SQLdown), it is practically unusable from the SQL side because it is stored in binary format. Would this problem still persist with MyDOWN @cshum ?

**Comment by mafintosh** [comment]
@karissa everything we do is wrapped in internal protobuf encodings so it would probably still be binary

**Comment by max-mapper** [comment]
I think the idea would be to map the protobuf into mysql types. would be pretty cool to have the mysql tables be 'idiomatic'

**Comment by okdistribute** [comment]
Ah yeah, this would be pretty nice

**Comment by max-mapper** [comment]
I think maybe we are discussing 2 different use cases here: one is running dat-core on mysql (for when you e.g. only have access to a mysql database and not leveldb), another is syncing a subset of dat data into a mysql table (for general purpose use)

**Comment by okdistribute** [comment]
@maxogden right. and we definitely have support for the 1st right now.

So, this PR would be a step address the second point, it seems. The 'syncing' data to a mysql table could be done externally (through a changes/SLEEP feed, as we've discussed), or like this -- but we still don't have the second piece, which is mapping protobufs to sql..

**Comment by cshum** [comment]
Before coming up with this PR there are several ways considered:
- Simply use one table. Doesn't sound right for sql database. Also MySQL unique key has a 767 bytes limit by default, which is easy to reach if we have lots of sublevels.
- Reverse engineer key prefix to figure out the sql tables it belongs to. Table joins when we need a full scan of database. This sounds complicated and super easy to go wrong.
- PR subleveldown for such changes. But since it appends `!` padding manually for `.batch()`, changing this behaviour means incompatibility for many of its dependent projects.

**Comment by cshum** [comment]
Regarding to single table usage, it should be testable without making any changes to dat-core:

``` js
var mydown = require('mydown')('db', { //uses mysql db `db`
  host: 'localhost',
  user: 'root'
}) 
var db = dat('/some/regular/path', {
  backend: function () {
    return mydown('dat'); //uses table `dat`
  }
})
```

**Comment by cshum** [comment]
@karissa the value needs to be protobuf to be compatible with [abstract leveldown](https://github.com/Level/abstract-leveldown). 

``` js
levelup('dat', {
  db: mydown,
  schema: ...
})
```

It may be possible to specify schema but that will be too much hassle as a LevelUP backend.

Another notable backend though, PostgreSQL supports JSON types. 
http://www.postgresql.org/docs/9.4/static/datatype-json.html
Combined with tables it should be pretty usable for PostgreSQL side.

**Comment by cshum** [comment]
One hassle of PostgreSQL backend though is `put()`. 
Because UPSERT is surprisingly difficult for SQL databases.
While MySQL has `INSERT ... ON DUPLICATE KEY UPDATE` there is no much reliable equivalent to PostgreSQL:
https://wiki.postgresql.org/wiki/UPSERT#UPSERT_as_implemented_in_practice

However PostgreSQL 9.5 added UPSERT support, which means this will also be fixed.
https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29

**Comment by max-mapper** [comment]
@cshum we're doing a video call in a couple days: https://github.com/datproject/discussions/issues/25 if you can join it would be awesome to talk about this. otherwise we can schedule a separate call to discuss ideas, i think this is one of this topics that voice chat would be much better for :)

**Comment by cshum** [comment]
@maxogden I would really love to join the discussion, but that's 1am here. Guess I should watch the video and catch up later on. Many thanks!

**Pull request closed without merging**
