### PR TITLE
Fix small bugs with dataset references

### PR DESCRIPTION
**Pull request by okdistribute**

### CODE REVIEW

**Comment by mafintosh** [comment]
Do we need set the 'default' string in .put/batch etc as well or did you just find the bug in merge?

**Comment by okdistribute** [comment]
We might not need it.

**Comment by mafintosh** [comment]
Turns out the 'default' string breaks the other methods since the default dataset is represented by the empty string internally. Could you remove that so we can fix the other (embarrassing) bug?

I'm up for changing the dataset thing but we should discuss that in another PR so we can fix it everywhere if we want to name it "default" on disk.

**Comment by mafintosh** [comment]
You can access the default dataset by either using the put/get methods on the dat-core object for by doing `defaultSet = dat.dataset()` btw

**Comment by okdistribute** [comment]
going to delete the branch, we should probably stay in the habit of this

**Pull request merged**
